djangoTesting/djangoTesting/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('hello/', views.hello)
]

djangoTesting/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.IndexView.as_view(template_name="posts/index.html"),
        name='index'
    ),
    # path(
    #     '<int:pk>/',
    #     views.DetailView.as_view(template_name="posts/detail.html"),
    #     name='detail'
    # ),
    path('<int:comment_id>/', views.detail, name='detail'),
    path(
        '<int:post_id>/comment/',
        views.comment,
        name='comment'
    ),
    path(
        'new/',
        views.post,
        name='post'
    ),
    path(
        '<int:post_id>/create-comment/',
        views.createComment,
        name='create-comment'
    ),
    path(
        'create-post/',
        views.createPost,
        name='create-post'
    ),
    path(
        '<int:post_id>/results/',
        views.results,
        name='results'
    ),
    path(
        '<int:comment_id>/vote/',
        views.vote,
        name='vote'
    ),
]

djangoTesting/posts/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    post_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.post_text

    def was_published_recently(self):
        """
        antes tenia este codigo:
            return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        pero tenia un bug que si pongo una fecha futura no mostraba un error
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.comment_text

djangoTesting/djangoTesting/views.py
from django.shortcuts import render

def hello(request):
  return render(request, 'hello.html')

djangoTesting/posts/views.py
from django.http.response import Http404, HttpResponseRedirect
from .models import Comment, Post
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'latest_post_list'

    def get_queryset(self):
        """Return the last five published questions."""
        # return Post.objects.order_by('-pub_date')[:5]
        return Post.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

# def index(request):
#     latest_post_list = Post.objects.order_by('-pub_date')[:5]
#     context = {'latest_post_list': latest_post_list}
#     return render(request, 'posts/index.html', context)

def detail(request, comment_id):
    # return HttpResponse("You're looking at comment %s." % comment_id)
    try:
        comment = Comment.objects.get(id=comment_id)
    except Comment.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'posts/detail.html', {'comment': comment})


# class DetailView(generic.DetailView):
#     model = Comment
#     template_name = 'posts/detail.html'


class ResultsView(generic.ListView):
    model = Post
    template_name = 'posts/results.html'

def comment(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
    except Comment.DoesNotExist:
        raise Http404("Post does not exist")
    return render(request, 'posts/comment.html', {'post': post})

def post(request):
    return render(request, 'posts/post.html', {})


def createComment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = Comment(post=post, comment_text=request.POST['comment'], pub_date=timezone.now())
    comment.save()
    return HttpResponseRedirect(reverse('posts:results', args=(post.id,)))


def createPost(request):
    post = Post(post_text=request.POST['post'], pub_date=timezone.now())
    post.save()
    return HttpResponseRedirect('/posts')


def results(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post=post)
    return render(
        request,
        'posts/results.html',
        {'post': post, 'comments': comments}
    )
    # response = "You're looking at the results of comment %s."
    # return HttpResponse(response % comment_id)

def vote(request, comment_id):
    return HttpResponse("You're voting on comment %s." % comment_id)


class DetailView(generic.DetailView):

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Post.objects.filter(pub_date__lte=timezone.now())

djangoTesting/posts/templates/hello.html
{% extends "layout.html" %}


{% block content %}

    <div class="container-sm">
        <h1>Hola a todos desde la app poster en 29 de diciembre</h1>
    </div>

{% endblock content %}

djangoTesting/posts/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %}{% endblock title %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light p-3 mb-2 bg-dark text-white">
      <div class="container-fluid">
        <a style="width:100%; text-align:center" class="navbar-brand text-white" href="/posts">Poster</a>
      </div>
    </nav>


    {% block content %}

    {% endblock content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

djangoTesting/posts/templates/posts/comment.html
<form action="{% url 'posts:create-comment' post.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ post.post_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label for="comment">Escribe tu comentario</label><br>
    <input type="text" name="comment" id="choice">
</fieldset>
<input type="submit" value="Guardar">
</form>

djangoTesting/posts/templates/posts/detail.html
{% extends "layout.html" %}


{% block content %}

    <div class="container-sm	">
        {{ comment }}

    </div>

{% endblock content %}

djangoTesting/posts/templates/posts/index.html
{% extends "layout.html" %}

{% block content %}

    <div class="container-sm	">
    {% if latest_post_list %}
      <ul class="">
      {% for post in latest_post_list %}
          <li class="card-body">
            <span >
              {{ post.post_text }} ({{ post.pub_date }})
            </span>
            <a class="btn btn-info" href="/posts/{{post.id}}/results">
              Ver comentarios
            </a>
            <a  class="btn btn-primary" href="{% url 'posts:comment' post.id %}">
              comentar
            </a>
          </li>
      {% endfor %}
      </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}


        <div>
        <a  class="btn btn-primary" href="/posts/new">
          Crear nuevo post
        </a>
      </div>

    </div>



{% endblock content %}

djangoTesting/posts/templates/posts/post.html
{% extends "layout.html" %}


{% block content %}

    <div class="container-sm	">
        <form action="{% url 'posts:create-post' %}" method="post">
        {% csrf_token %}
        <fieldset>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label for="post">Escribe tu post</label><br>
            <input class="form-control" type="text" name="post" id="choice">
        </fieldset>
        <input  class="btn btn-primary" type="submit" value="Guardar">
        </form>

        <a  class="btn btn-secondary" href="/posts">Regresar</a>

        
    </div>

{% endblock content %}

djangoTesting/posts/templates/posts/results.html
{% extends "layout.html" %}


{% block content %}

    <div class="container-sm	">
<h1>{{ post.post_text }} ({{ post.pub_date }})</h1>

<ul>
{% for comment in comments %}
    <li>{{ comment.comment_text}} ({{comment.pub_date}})</li>
{% endfor %}
</ul>


    <a class="btn btn-primary" href="{% url 'posts:comment' post.id %}">
        Nuevo comentario
    </a>
    <a  class="btn btn-secondary" href="/posts">Regresar</a>

    </div>

{% endblock content %}